# Acordeón de pandas

En esta nota veremos ejemplos de los comandos básicos de pandas utilizando una base de datos genérica.

El primer paso es importar la librería pandas como se muestra en la siguiente celda.

In [2]:
import pandas as pd

## Leer un archivo .csv

Para extraer la información de un archivo .csv es necesarop tener el archivo en la misma carpeta que esta nota, para el ejemplo de hoy usaremos el archivo `base_generica_pandas.csv`. Un archivo se lee utilizando el método `read_csv("nombre del archivo")` y guardarlo en una variable llamada `df`

In [3]:
df = pd.read_csv("base_generica_pandas.csv")

Para explorar esta base podemos utilizar el método `head()` para mostar las primeras 5 filas de la tabla, si quisieramos ver `n` filas podemos usat `head(n)`.
Entre paréntesis podemos poner el número de filas que queremos, el determinado es 5.

In [4]:
df.head()

     col1  col2  col3  col4 col5   col6   col7  col8 col9  col10
0  380.79    49  56.4     1    B    Sur  0.294     5   No   Alto
1  951.21    56  13.0     9    A  Oeste  0.996     2   Sí  Medio
2  734.67    49  57.2     2    C  Norte  0.697     5   Sí   Alto
3  602.67    21  63.9     0    A  Norte  0.384     3   Sí   Alto
4  164.46    47  37.4     7    D    Sur  0.737     3   Sí  Medio

El método tail muestra los últimos 5 elementos por default, pero es posible mostra los últimos n

In [5]:
df.tail()

      col1  col2  col3  col4 col5   col6   col7  col8 col9 col10
95  498.86    43  47.7     8    B    Sur  0.459     2   Sí  Bajo
96  527.51    20  44.4     6    C   Este  0.842     2   Sí  Alto
97  433.27    36  30.6     3    D  Norte  0.769     3   Sí  Bajo
98   35.16    37  38.5     9    A  Norte  0.066     3   Sí  Bajo
99  116.81    49  56.3     4    B    Sur  0.046     5   Sí  Bajo

El tamaño de la tabla se muestra con `.shape`. Donde el primer número representa la cantidad de filas mientras la segunda cantidad representa la cantidad de columnas.

In [6]:
df.shape
# este data frame tiene 100 filas y 10 columnas

(100, 10)

El nombre de las columnas de un dataframe es accesible a través del atributo `.columns`

In [7]:
df.columns

Index(['col1', 'col2', 'col3', 'col4', 'col5', 'col6', 'col7', 'col8', 'col9',
       'col10'],
      dtype='str')

El método `info()` muestra una tabla con la información de la tabla:
* nombre de la columna
* cantidad de nulos
* tipos de datos
* espacio en memoria (RAM)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    100 non-null    float64
 1   col2    100 non-null    int64
 2   col3    100 non-null    float64
 3   col4    100 non-null    int64
 4   col5    100 non-null    str
 5   col6    100 non-null    str
 6   col7    100 non-null    float64
 7   col8    100 non-null    int64
 8   col9    100 non-null    str
 9   col10   100 non-null    str
dtypes: float64(3), int64(3), str(4)
memory usage: 7.9 KB

## Manejo de columnas
Es posible seleccionar una o varias columnas:
* Una columna
* Dos columnas
* Una lista de columnas

La sintaxis general es `df[las columnas que quiero]`

### Ejemplo para una columna

Para seleccionar la columna `col15` usamos `df["col5]`

In [9]:
# "col5" es el nombre de la columna, no sintaxis interna de python
df[["col5"]]

   col5
0     B
1     A
2     C
3     A
4     D
..  ...
95    B
96    C
97    D
98    A
99    B

[100 rows x 1 columns]

### Ejemplo para dos columnas
Para seleccionar dos columnas la sintaxis general es `df[["col8", "col7"]]`, la diferencia con seleccionar una columna es que en esta ocasión hay doble corchete:

In [10]:
# "col8" y "col7" son nombres de las columnas no sintaxis de python
df[["col8", "col7"]]

    col8   col7
0      5  0.294
1      2  0.996
2      5  0.697
3      3  0.384
4      3  0.737
..   ...    ...
95     2  0.459
96     2  0.842
97     3  0.769
98     3  0.066
99     5  0.046

[100 rows x 2 columns]

### Ejemplo para seleccionar varias columnas
En general para seleccionar varias columnas es necesario escribir la *lista* de las columnas y pasarlas con corchetes al dataframe, por ejemplo, si queremos las columnas `col1`, `col10`, `col6` y `col8`, podemos utilizar la siguiente sintaxis

In [11]:
columnas_seleccionadas = ["col1", "col10", "col6", "col8"]
df[columnas_seleccionadas]

      col1  col10   col6  col8
0   380.79   Alto    Sur     5
1   951.21  Medio  Oeste     2
2   734.67   Alto  Norte     5
3   602.67   Alto  Norte     3
4   164.46  Medio    Sur     3
..     ...    ...    ...   ...
95  498.86   Bajo    Sur     2
96  527.51   Alto   Este     2
97  433.27   Bajo  Norte     3
98   35.16   Bajo  Norte     3
99  116.81   Bajo    Sur     5

[100 rows x 4 columns]

## Filtrar Datos

Al crear una condición sobre una columna estamos creando una máscara lógica (una columna de True o False por cada fila que cumpla la condición), por ejemplo `df["col6"]=="Sur"` crea una columna que será True en aquellas filas donde el valor sea "Sur" y False cuando no lo sea.

In [12]:
df["col6"] == "Sur"

0      True
1     False
2     False
3     False
4      True
      ...
95     True
96    False
97    False
98    False
99     True
Name: col6, Length: 100, dtype: bool

Para acceder a la tabla completa en la que se cumpla la condición `df["col6] == "Sur"` sólo basta con agregarlo entre corchetes al dataframe: `df[df["col6] == "Sur"]`. El resultado contiene las filas y columnas del dataframe en las cuales la columna `col16` tenga el valor "Sur"

In [13]:
df[df["col6"] == "Sur"]

      col1  col2  col3  col4 col5 col6   col7  col8 col9  col10
0   380.79    49  56.4     1    B  Sur  0.294     5   No   Alto
4   164.46    47  37.4     7    D  Sur  0.737     3   Sí  Medio
6    67.50    40  78.1     9    A  Sur  0.959     3   Sí   Bajo
9   710.99    32  42.2     4    A  Sur  0.107     4   Sí  Medio
11  970.21    46  55.7     4    B  Sur  0.170     1   No   Bajo
13  220.22    30  57.5     8    A  Sur  0.388     3   Sí   Bajo
14  190.01    49  47.8     4    D  Sur  0.229     3   No  Medio
18  437.63    19  51.6     0    C  Sur  0.453     2   No  Medio
24  461.51    61  22.3     0    D  Sur  0.133     4   Sí  Medio
33  949.40    18  33.3     5    A  Sur  0.165     2   No  Medio
39  445.75    23  52.2     9    A  Sur  0.750     2   Sí   Alto
42   44.04    26  49.8     6    D  Sur  0.569     3   No   Bajo
43  910.23    54  56.2     3    D  Sur  0.064     5   Sí  Medio
46  318.59    61  69.5     6    A  Sur  0.014     4   No   Alto
50  969.89    49  49.9     4    D  Sur  0.750     5   No   Bajo
52  940.10    58  72.2     1    A  Sur  0.585     2   Sí   Alto
53  895.88    29  56.0     3    A  Sur  0.726     4   No   Alto
65  547.27    50  23.8     0    C  Sur  0.022     3   Sí  Medio
73  817.31    49  43.3     2    C  Sur  0.792     2   Sí   Bajo
75  731.72    28  39.1     4    D  Sur  0.480     1   No   Bajo
76  773.56    34  23.0     2    A  Sur  0.421     1   Sí   Bajo
85  331.93    33  80.0     2    C  Sur  0.555     2   Sí  Medio
95  498.86    43  47.7     8    B  Sur  0.459     2   Sí   Bajo
99  116.81    49  56.3     4    B  Sur  0.046     5   Sí   Bajo

Para condiciones numéricas ocurre lo mismo, podemos utilizar operadores como `>, <, ==, !=, >=, <=`. Por ejemplo, para obtener las filas y columnas del dataframe que cumplan que `col1` tenga un valor mayor a 500 utilizamos `df[df["col1"] > 500]`

In [14]:
df[df["col1"] > 500]

      col1  col2  col3  col4 col5   col6   col7  col8 col9  col10
1   951.21    56  13.0     9    A  Oeste  0.996     2   Sí  Medio
2   734.67    49  57.2     2    C  Norte  0.697     5   Sí   Alto
3   602.67    21  63.9     0    A  Norte  0.384     3   Sí   Alto
7   867.51    56  55.9     6    A  Norte  0.058     1   No   Bajo
8   605.10    62  40.6     9    A  Oeste  0.395     3   No  Medio
9   710.99    32  42.2     4    A    Sur  0.107     4   Sí  Medio
11  970.21    46  55.7     4    B    Sur  0.170     1   No   Bajo
12  834.12    53  50.9     6    A   Este  0.647     3   No   Alto
17  529.51    45  34.0     9    A  Norte  0.260     5   Sí   Bajo
20  615.73    62  63.8     5    D  Oeste  0.280     3   Sí   Alto
25  787.32    61  67.5     6    D  Oeste  0.076     2   No   Alto
27  519.09    47  33.6     5    B   Este  0.417     5   No   Bajo
28  596.49    28   6.8     6    D   Este  0.581     1   No   Bajo
30  611.47    42  49.9     9    D  Norte  0.083     1   No   Alto
33  949.40    18  33.3     5    A    Sur  0.165     2   No  Medio
34  965.98    44  63.0     8    C  Oeste  0.411     1   Sí   Bajo
35  810.31    30  64.4     4    A   Este  0.778     2   No   Bajo
38  687.39    56  84.1     4    B  Oeste  0.377     1   No  Medio
41  500.23    44  27.5     4    B   Este  0.829     1   No   Alto
43  910.23    54  56.2     3    D    Sur  0.064     5   Sí  Medio
45  665.90    59  63.1     4    B   Este  0.134     2   Sí   Alto
47  524.87    41  29.8     9    C   Este  0.075     1   Sí   Alto
48  551.24    32  62.8     9    C  Norte  0.692     1   Sí   Bajo
50  969.89    49  49.9     4    D    Sur  0.750     5   No   Bajo
51  777.38    41  26.4     3    D  Oeste  0.913     4   Sí   Bajo
52  940.10    58  72.2     1    A    Sur  0.585     2   Sí   Alto
53  895.88    29  56.0     3    A    Sur  0.726     4   No   Alto
54  601.92    56  23.3     9    C  Oeste  0.757     2   Sí  Medio
55  922.66    19  46.4     9    D  Oeste  0.378     5   No  Medio
62  830.45    40  35.8     7    D   Este  0.757     5   No   Alto
65  547.27    50  23.8     0    C    Sur  0.022     3   Sí  Medio
67  804.18    36  25.7     3    A   Este  0.476     1   No   Alto
69  987.02    61  70.8     1    C  Norte  0.308     4   No   Bajo
70  774.52    43  37.2     2    D  Norte  0.816     2   No  Medio
73  817.31    49  43.3     2    C    Sur  0.792     2   Sí   Bajo
74  709.79    21  56.3    10    A  Norte  0.590     4   Sí  Medio
75  731.72    28  39.1     4    D    Sur  0.480     1   No   Bajo
76  773.56    34  23.0     2    A    Sur  0.421     1   Sí   Bajo
80  864.47    51  39.0     9    C  Norte  0.903     4   No   Alto
81  627.07    23  52.9    10    A  Norte  0.617     2   No   Bajo
86  732.31    50  32.0     6    B  Norte  0.091     4   No   Bajo
87  641.18    26  68.0     0    C   Este  0.726     2   No   Alto
88  888.34    23  52.2     9    B  Oeste  0.547     1   No  Medio
91  716.11    20  21.8     9    C   Este  0.298     2   No  Medio
92  763.18    37  64.5     9    A   Este  0.524     1   No   Bajo
93  565.66    53  42.3     1    C  Oeste  0.698     5   Sí   Alto
94  773.26    36  68.2     2    C  Norte  0.796     4   Sí   Alto
96  527.51    20  44.4     6    C   Este  0.842     2   Sí   Alto

### Filtrar por más de una condición
Para filtrar por más de una condición basta con separar las condiciones por paréntesis y conectarlos con los operadores lógicos `&` (and), `|` (or), `~` (not), ejemplo:
* Las filas cuya columna 6 sea "Sur" y columna 5 diferente de "B"
    * `(df["col6"] == "Sur") & (df["col5"] != "B")`
* Las filas cuya columna 5 sea "A" o columna 6 sea "Norte"
    * `(df["col5"] == "A") | (df["col6"] == "Norte")`

In [32]:
df[(df["col6"] == "Sur") & (df["col5"] != "B")]

,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col2_duplicada
4,164.46,47,37.4,7,D,Sur,0.737,3,Sí,Medio,94
6,67.50,40,78.1,9,A,Sur,0.959,3,Sí,Bajo,80
9,710.99,32,42.2,4,A,Sur,0.107,4,Sí,Medio,64
13,220.22,30,57.5,8,A,Sur,0.388,3,Sí,Bajo,60
14,190.01,49,47.8,4,D,Sur,0.229,3,No,Medio,98
18,437.63,19,51.6,0,C,Sur,0.453,2,No,Medio,38
24,461.51,61,22.3,0,D,Sur,0.133,4,Sí,Medio,122
33,949.40,18,33.3,5,A,Sur,0.165,2,No,Medio,36
39,445.75,23,52.2,9,A,Sur,0.750,2,Sí,Alto,46
42,44.04,26,49.8,6,D,Sur,0.569,3,No,Bajo,52
43,910.23,54,56.2,3,D,Sur,0.064,5,Sí,Medio,108
46,318.59,61,69.5,6,A,Sur,0.014,4,No,Alto,122
50,969.89,49,49.9,4,D,Sur,0.750,5,No,Bajo,98
52,940.10,58,72.2,1,A,Sur,0.585,2,Sí,Alto,116
53,895.88,29,56.0,3,A,Sur,0.726,4,No,Alto,58
65,547.27,50,23.8,0,C,Sur,0.022,3,Sí,Medio,100
73,817.31,49,43.3,2,C,Sur,0.792,2,Sí,Bajo,98
75,731.72,28,39.1,4,D,Sur,0.480,1,No,Bajo,56
76,773.56,34,23.0,2,A,Sur,0.421,1,Sí,Bajo,68
85,331.93,33,80.0,2,C,Sur,0.555,2,Sí,Medio,66

Además, `.loc` y `.iloc` también son muy importantes y útiles para filtrar datos, `.loc` sirve para seleccionar por etiqueta y `.iloc` para seleccionar por posición. Por ejemplo, si queremos las filas de 0 a 5 y las columnas `col1` y `col2` utilizamos `df.loc[0:5, ["col1", "col2"]]`.

In [16]:
df.loc[0:5, ["col1", "col2"]]

     col1  col2
0  380.79    49
1  951.21    56
2  734.67    49
3  602.67    21
4  164.46    47
5  164.43    54

Y si queremos las filas 2 a 6 y las columnas de posición 2 a 4 utilizamos `df.iloc[2:6, 2:4]`

In [17]:
df.iloc[2:6, 2:4]

   col3  col4
2  57.2     2
3  63.9     0
4  37.4     7
5  60.2     2

## Ordenar datos

Para ordenar datos de menor a mayor utilizamos `df.sort_values()`. Si queremos que se ordene la columna 1, sería `df.sort_values("col1")`

In [18]:
df.sort_values("col1")

      col1  col2  col3  col4 col5   col6   col7  col8 col9  col10
72   15.47    23  63.2     0    D  Norte  0.088     1   No   Alto
10   30.38    60  50.2     9    D  Norte  0.336     4   No  Medio
98   35.16    37  38.5     9    A  Norte  0.066     3   Sí   Bajo
42   44.04    26  49.8     6    D    Sur  0.569     3   No   Bajo
58   54.78    34  48.1     0    D   Este  0.251     3   No   Alto
..     ...   ...   ...   ...  ...    ...    ...   ...  ...    ...
1   951.21    56  13.0     9    A  Oeste  0.996     2   Sí  Medio
34  965.98    44  63.0     8    C  Oeste  0.411     1   Sí   Bajo
50  969.89    49  49.9     4    D    Sur  0.750     5   No   Bajo
11  970.21    46  55.7     4    B    Sur  0.170     1   No   Bajo
69  987.02    61  70.8     1    C  Norte  0.308     4   No   Bajo

[100 rows x 10 columns]

Si queremos que ordene de mayor a menor escribimos `ascending = False`. De esta forma sería `df.sort_values("col1", ascending = False)`.
En caso de no ser numérica, ordena de A a la Z.

In [19]:
df.sort_values("col1", ascending = False)

      col1  col2  col3  col4 col5   col6   col7  col8 col9  col10
69  987.02    61  70.8     1    C  Norte  0.308     4   No   Bajo
11  970.21    46  55.7     4    B    Sur  0.170     1   No   Bajo
50  969.89    49  49.9     4    D    Sur  0.750     5   No   Bajo
34  965.98    44  63.0     8    C  Oeste  0.411     1   Sí   Bajo
1   951.21    56  13.0     9    A  Oeste  0.996     2   Sí  Medio
..     ...   ...   ...   ...  ...    ...    ...   ...  ...    ...
58   54.78    34  48.1     0    D   Este  0.251     3   No   Alto
42   44.04    26  49.8     6    D    Sur  0.569     3   No   Bajo
98   35.16    37  38.5     9    A  Norte  0.066     3   Sí   Bajo
10   30.38    60  50.2     9    D  Norte  0.336     4   No  Medio
72   15.47    23  63.2     0    D  Norte  0.088     1   No   Alto

[100 rows x 10 columns]

Si queremos ordenar varias columnas, las escribimos en una lista, por ejemplo para ordenar de menor a mayor primero por `col1` y después por `col2` escribimos `df.sort_values(["col1", "col2"])`.

In [20]:
df.sort_values(["col1", "col2"])

      col1  col2  col3  col4 col5   col6   col7  col8 col9  col10
72   15.47    23  63.2     0    D  Norte  0.088     1   No   Alto
10   30.38    60  50.2     9    D  Norte  0.336     4   No  Medio
98   35.16    37  38.5     9    A  Norte  0.066     3   Sí   Bajo
42   44.04    26  49.8     6    D    Sur  0.569     3   No   Bajo
58   54.78    34  48.1     0    D   Este  0.251     3   No   Alto
..     ...   ...   ...   ...  ...    ...    ...   ...  ...    ...
1   951.21    56  13.0     9    A  Oeste  0.996     2   Sí  Medio
34  965.98    44  63.0     8    C  Oeste  0.411     1   Sí   Bajo
50  969.89    49  49.9     4    D    Sur  0.750     5   No   Bajo
11  970.21    46  55.7     4    B    Sur  0.170     1   No   Bajo
69  987.02    61  70.8     1    C  Norte  0.308     4   No   Bajo

[100 rows x 10 columns]

## Estadísticas descriptivas

Para obtener la estadística de una columna basta con seleccionar la columna y aplicar el método, por ejemplo, la media es `.mean()`, el máximo es `.max()`, el mínimo es `.min()` la mediana `.median()` y la desviación estándar es `.std()`.

Tenemos entonces tomando de ejemplo la columna 1:
* `df["col1"].mean()` calcula la media (promedio aritmético) de la columna 1
* `df["col1"].median()` calcula la mediana de la columna 1
* `df["col1"].min()` calcula el valor más pequeño de la columna 1
* `df["col1"].max()` calcula el valor más grande de la columna 1
* `df["col1"].std()` calcula qué tan dispersos están los datos respecto a la media en la columna 1

In [21]:
print("promedio:")
display(df["col1"].mean())

print("mediana:")
display(df["col1"].median())

print("mínimo:")
display(df["col1"].min())

print("máximo:")
display(df["col1"].max())

print("desviación estándar:")
display(df["col1"].std())

promedio:

np.float64(475.4793000000001)

mediana:

np.float64(469.5)

mínimo:

np.float64(15.47)

máximo:

np.float64(987.02)

desviación estándar:

np.float64(294.5145254165289)

Además, `.describe()` proporciona estadísticas de las columnas numéricas, `count` brinda información sobre el número total de valores válidos sin contar los valores nulos. Así como promedio, desviación estándar, mínimo, máximo, primer, segundo y tercer cuartil.

In [22]:
df.describe()

             col1        col2        col3       col4        col7        col8
count  100.000000  100.000000  100.000000  100.00000  100.000000  100.000000
mean   475.479300   40.650000   48.323000    4.72000    0.493950    2.900000
std    294.514525   13.699056   15.726294    3.26314    0.291855    1.396243
min     15.470000   18.000000    6.800000    0.00000    0.014000    1.000000
25%    201.267500   28.000000   37.350000    2.00000    0.264500    2.000000
50%    469.500000   43.000000   49.900000    4.00000    0.480000    3.000000
75%    732.900000   50.250000   57.525000    8.00000    0.751750    4.000000
max    987.020000   65.000000   84.100000   10.00000    0.996000    5.000000

## Trabajar con variables categóricas

En caso de que nuestras variables sean categóricas utilizamos `value_counts()` para saber cuántas veces aparece cada categoría, por ejemplo, para la columna 6 sería `df["col6"].value_counts()`.

In [23]:
df["col6"].value_counts()

col6
Norte    33
Sur      24
Oeste    22
Este     21
Name: count, dtype: int64

Utilizamos `unique()` para saber cuáles son las categorías de una columna, para la columna 6, sería `df["col6"].unique()`

In [24]:
df["col6"].unique()

<StringArray>
['Sur', 'Oeste', 'Norte', 'Este']
Length: 4, dtype: str

Y utilizamos `nunique()` para saber cuántas categorías diferentes existen `df["col6"].nunique()`

In [25]:
df["col6"].nunique()

4

## Agrupar datos

Podemos clasificar y agrupar por categorías en una columna y realizar operaciones para cada una de ellas con `groupby()`. Por ejemplo, si quisieramos agrupar la columa 10 y calcular el promedio de la columna 1 escribiríamos `df.groupby("col10")["col1"].mean()`. Primero escribimos la columna que queremos agrupar y luego la columna sobre la que queremos realizar la operación.

In [26]:
df.groupby("col10")["col1"].mean()

col10
Alto     480.194412
Bajo     473.109722
Medio    472.979000
Name: col1, dtype: float64

También podemos calcular sobre dos o más columnas, creando una lista de columnas, en el siguiente ejemplo queremos agrupar por las categorías de la columna 10 y calcular el promedio de la columna 1 y 3 utilizando `df.groupby("col10")[["col1", "col3"]].mean()`

In [27]:
df.groupby("col10")[["col1", "col3"]].mean()

             col1       col3
col10
Alto   480.194412  51.141176
Bajo   473.109722  46.633333
Medio  472.979000  47.156667

Y podemos agrupar por dos o más columnas, también escribiendo una lista de columnas, por ejemplo, para clasificar por la columna 10 y 5, utilizamos `df.groupby(["col10", "col5"])[["col1", "col3"]].mean()`

In [28]:
df.groupby(["col10", "col5"])[["col1", "col3"]].mean()

                  col1       col3
col10 col5
Alto  A     522.872000  50.530000
      B     433.426000  50.080000
      C     551.003000  51.200000
      D     380.081111  52.344444
Bajo  A     388.628125  49.618750
      B     497.563333  45.316667
      C     602.088333  55.350000
      D     526.998750  35.112500
Medio A     571.715000  41.187500
      B     491.630000  52.750000
      C     391.672000  50.350000
      D     466.551250  46.337500

Para realizar conteos por categoría podemos usar `.count()`, por ejemplo para agrupar con las columnas 5, 10, y 9 y contar cuántas filas hay por cada categoría en la columna 1, podemos utilizar `df.groupby(["col5", "col10", "col9"])[["col1"]].count()`

In [29]:
df.groupby(["col5", "col10", "col9"])[["col1"]].count()

                 col1
col5 col10 col9
A    Alto  No       4
           Sí       6
     Bajo  No       9
           Sí       7
     Medio No       5
           Sí       3
B    Alto  No       3
           Sí       2
     Bajo  No       3
           Sí       3
     Medio No       3
           Sí       1
C    Alto  No       4
           Sí       6
     Bajo  No       1
           Sí       5
     Medio No       5
           Sí       5
D    Alto  No       7
           Sí       2
     Bajo  No       4
           Sí       4
     Medio No       4
           Sí       4

## Crear y modificar columnas

Podemos crear nuevas columnas a partir de otras existentes, por ejemplo, si queremos duplicar los valores de la columna 2, utilizaremos `df["col2_duplicada"] = df["col2"] * 2`. Obtendremos una nueva columna que cumpla con las características que deseamos.

In [30]:
df["col2_duplicada"] =df["col2"] * 2
df.head()

,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col2_duplicada
0,380.79,49,56.4,1,B,Sur,0.294,5,No,Alto,98
1,951.21,56,13.0,9,A,Oeste,0.996,2,Sí,Medio,112
2,734.67,49,57.2,2,C,Norte,0.697,5,Sí,Alto,98
3,602.67,21,63.9,0,A,Norte,0.384,3,Sí,Alto,42
4,164.46,47,37.4,7,D,Sur,0.737,3,Sí,Medio,94

## Combinar operaciones

Después de aprender a utilizar las funciones anteriores, podemos combinarlas para crear diferentes soluciones. 
Por ejemplo, podemos agrupar por las columnas 6 y 10, y calcular el promedio de la columna 1 y tomar las que son mayores a 500.

In [31]:
promedio = df.groupby(["col6", "col10"])[["col1"]].mean()
promedio[promedio["col1"] > 500]

                   col1
col6  col10
Este  Alto   554.765000
      Bajo   542.263333
Oeste Medio  535.611000
Sur   Alto   596.222000
      Bajo   521.012000
      Medio  522.603333