In [2]:
import pandas as pd 
df = pd.read_csv("https://raw.githubusercontent.com/vida092/diplomado_big_data/refs/heads/main/peliculas.csv")

In [3]:
df

,id,titulo,fecha_estreno,genero,duracion_min,presupuesto_musd,taquilla_musd,popularidad,rating,votos,idioma_original,adulto
0,1711051,100 Years,2099-12-31,Sin género,0,0.0,0.0,0.26,0.0,0,en,False
1,1742644,American Static,2047-05-11,Ciencia ficción,186,0.0,0.0,0.24,0.0,0,en,False
2,1742657,September,2045-07-08,Terror,140,0.0,0.0,0.25,0.0,0,en,False
3,1370697,Light Years,2044-10-01,Sin género,7,0.0,0.0,0.69,0.0,0,en,False
4,1742658,Harvest,2043-10-03,Terror,184,0.0,0.0,0.21,0.0,0,en,False
...,...,...,...,...,...,...,...,...,...,...,...,...
95,806704,Batman: Parte 2,2028-02-17,Misterio,0,0.0,0.0,5.52,0.0,0,en,False
96,1662286,Золушка,2028-02-10,Sin género,0,0.0,0.0,0.94,0.0,0,ru,False
97,1625381,Heart Eyes 2,2028-02-10,Terror,0,0.0,0.0,0.51,0.0,0,en,False
98,1188748,"Murder, She Wrote",2028-02-03,Misterio,0,0.0,0.0,0.63,0.0,0,en,False
99,1634592,Endless Summer,2028-01-28,Drama,130,0.0,0.0,1.61,0.0,0,en,False

In [4]:
# 1 y 2
df.shape

(100, 12)

In [5]:
# 3
df.columns

Index(['id', 'titulo', 'fecha_estreno', 'genero', 'duracion_min',
       'presupuesto_musd', 'taquilla_musd', 'popularidad', 'rating', 'votos',
       'idioma_original', 'adulto'],
      dtype='str')

In [6]:
#4
df.dtypes

id                    int64
titulo                  str
fecha_estreno           str
genero                  str
duracion_min          int64
presupuesto_musd    float64
taquilla_musd       float64
popularidad         float64
rating              float64
votos                 int64
idioma_original         str
adulto                 bool
dtype: object

In [7]:
#5 y 6
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                100 non-null    int64
 1   titulo            100 non-null    str
 2   fecha_estreno     100 non-null    str
 3   genero            100 non-null    str
 4   duracion_min      100 non-null    int64
 5   presupuesto_musd  100 non-null    float64
 6   taquilla_musd     100 non-null    float64
 7   popularidad       100 non-null    float64
 8   rating            100 non-null    float64
 9   votos             100 non-null    int64
 10  idioma_original   100 non-null    str
 11  adulto            100 non-null    bool
dtypes: bool(1), float64(4), int64(3), str(4)
memory usage: 8.8 KB

# Respuesta a las preguntas:
1. ¿Cuántas películas hay en el dataset?
100

2. ¿Cuántas variables o columnas contiene el dataset?
12

3. ¿Cuáles son las columnas que contiene el DataFrame?
'id', 'titulo', 'fecha_estreno', 'genero', 'duracion_min', 'presupuesto_musd', 'taquilla_musd', 'popularidad', 'rating', 'votos',
'idioma_original', 'adulto'

4. ¿Qué tipo de dato tiene cada columna?
dtypes: bool(1), float64(4), int64(3), str(4)

5. ¿Existen valores faltantes en el dataset?
No

6. ¿Cuánta información contiene cada columna?
100

7. ¿Qué columnas contienen información numérica?
'id', 'duracion_min', 'presupuesto_musd', 'taquilla_musd', 'popularidad', 'rating', 'votos'

8. ¿Qué columnas contienen información categórica o textual?
'titulo', 'fecha_estreno', 'genero', 'idioma_original', 'adulto'

In [8]:
# 9.Obtén únicamente la columna que contiene el título de las películas.
df[["titulo"]]

               titulo
0           100 Years
1     American Static
2           September
3         Light Years
4             Harvest
..                ...
95    Batman: Parte 2
96            Золушка
97       Heart Eyes 2
98  Murder, She Wrote
99     Endless Summer

[100 rows x 1 columns]

In [9]:
# 10. Obtén únicamente la columna que contiene el rating de las películas.
df[["rating"]]

    rating
0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
..     ...
95     0.0
96     0.0
97     0.0
98     0.0
99     0.0

[100 rows x 1 columns]

In [10]:
# 11. Obtén únicamente las columnas correspondientes al título, género y rating.
df[["titulo", "genero", "rating"]]

               titulo           genero  rating
0           100 Years       Sin género     0.0
1     American Static  Ciencia ficción     0.0
2           September           Terror     0.0
3         Light Years       Sin género     0.0
4             Harvest           Terror     0.0
..                ...              ...     ...
95    Batman: Parte 2         Misterio     0.0
96            Золушка       Sin género     0.0
97       Heart Eyes 2           Terror     0.0
98  Murder, She Wrote         Misterio     0.0
99     Endless Summer            Drama     0.0

[100 rows x 3 columns]

In [11]:
# 12. Obtén las estadísticas descriptivas de las variables numéricas.
df.describe()

,id,duracion_min,presupuesto_musd,taquilla_musd,popularidad,rating,votos
count,1.000000e+02,100.000000,100.0000,100.0,100.000000,100.0,100.0
mean,1.479390e+06,21.730000,8.1805,0.0,1.385000,0.0,0.0
std,3.080932e+05,50.850316,29.3839,0.0,2.069646,0.0,0.0
min,2.165270e+05,0.000000,0.0000,0.0,0.010000,0.0,0.0
25%,1.363082e+06,0.000000,0.0000,0.0,0.320000,0.0,0.0
50%,1.582366e+06,0.000000,0.0000,0.0,0.640000,0.0,0.0
75%,1.712100e+06,0.000000,0.0000,0.0,1.645000,0.0,0.0
max,1.752779e+06,186.000000,190.0000,0.0,14.950000,0.0,0.0

In [12]:
# 13. ¿Cuál es el rating promedio de las películas?
df["rating"].mean()

np.float64(0.0)

In [13]:
# 14. ¿Cuál es la duración promedio de las películas?
df["duracion_min"].mean()

np.float64(21.73)

In [19]:
# 15. ¿Cuál es la película con mayor duración?
df[df["duracion_min"] == df["duracion_min"].max()][["titulo"]]

            titulo
1  American Static

In [15]:
# 16. ¿Cuál es la película con mayor rating?
df[df["rating"] == df["rating"].max()][["titulo"]]

               titulo
0           100 Years
1     American Static
2           September
3         Light Years
4             Harvest
..                ...
95    Batman: Parte 2
96            Золушка
97       Heart Eyes 2
98  Murder, She Wrote
99     Endless Summer

[100 rows x 1 columns]

In [16]:
# 17. ¿Cuál es la película que recibió más votos?
df[df["votos"] == df["votos"].max()][["titulo"]]

               titulo
0           100 Years
1     American Static
2           September
3         Light Years
4             Harvest
..                ...
95    Batman: Parte 2
96            Золушка
97       Heart Eyes 2
98  Murder, She Wrote
99     Endless Summer

[100 rows x 1 columns]

In [17]:
# 18. ¿Qué géneros aparecen en el dataset y cuántas películas hay de cada género?
df["genero"].value_counts()

genero
Drama              16
Terror             15
Animación          14
Sin género         12
Acción              9
Ciencia ficción     6
Crimen              6
Fantasía            5
Aventura            4
Documental          2
Comedia             2
Familia             2
Suspense            2
Misterio            2
Bélica              1
Romance             1
Historia            1
Name: count, dtype: int64

La base de datos no tiene información de país ni plataforma, por lo que las preguntas 19 y 20 marcan error.

In [18]:
# 19. ¿Qué país aparece con mayor frecuencia?
df[df["pais"] == df["pais"].max()]["titulo"]

KeyError: 'pais'

In [ ]:
# 20. ¿Qué plataforma tiene más películas?
df[df["plataforma"] == df["plataforma"].max()]["titulo"]

KeyError: 'plataforma'

# Reflexión
* ¿Qué método de Pandas te resultó más útil?
Funciones como group by y las operaciones.

* ¿Qué operación te costó más trabajo?
Obtener un dato en específico, como el nombre de una película.

* ¿Qué información sobre el dataset descubriste que no esperabas?
Las películas que recibieron más votos.